# Generated by Django 4.2.7 on 2023-12-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nostafflocation',
            name='telephone_Number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='stafflocation',
            name='telephone_Number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
